### ISSUE TITLE
Control.lua v7.2 

### ISSUE THREAD

**Issue by dakkinbyte** [Mattie112/FactoriGOChatBot-companion#1]
Hello @Mattie112, 

Pulled the latest configuration for this mod via the factorio mod store. I found a bug in v7.2 but it only looks like you have 7.0 released here specifically. 

Inside of the control.lua file within this function

```
script.on_event(
    defines.events.on_rocket_launched,
    function(event)
        global.rocketLaunched = global.rocketLaunched or 0
        global.rocketLaunched = global.rocketLaunched + 1
        log_message("[ROCKET_LAUNCHED:" .. global.rocketLaunched .. "]")
    end
)
```

It will throw the following error message: 

```
Error while running event FactoriGOChatBot-companion::on_rocket_launched (ID 10)
__FactoriGOChatBot-companion__/control.lua:33: attempt to perform arithmetic on field 'rocketLaunched' (a table value)
stack traceback:
	__FactoriGOChatBot-companion__/control.lua:33: in function <__FactoriGOChatBot-companion__/control.lua:31>
```

The reason for this is due to the fact of this line at the bottom: 

```
local function initStorage()
    global.playerDeathCount = global.playerDeathCount or {}
    global.rocketLaunched = global.playerDeathCount or 0
end
```

Where you have the rocket launched referencing the playerDeathCount. It needs to be changed to 

```
local function initStorage()
    global.playerDeathCount = global.playerDeathCount or {}
    global.rocketLaunched = global.rocketLaunched or 0
end
```

Is this possible you can get this updated as well as a minor version push on the factorio mod store so this can download correctly? Have a few of my users who play on my server that are unable to connect with the corrected version that i put on there because it references back to yours. 

Thanks very much. 

- Dakkin

**Comment by Mattie112** [comment]
Hi,

I am sorry for the late reply. Thanks for fixing this issue I will have a look as soon as I can!

**Comment by Mattie112** [comment]
The change you are suggesting seems to be correct indeed. I am not sure what happend with v7.2 I might have forgot to push someting from my home PC the last time I worked on this. So am sorry this will take a bit of extra time till I can check that from home. Don't want to use a possible outdated version :)

**Comment by Mattie112** [comment]
And due to being sick it took even longer :)

But here it is:
https://github.com/Mattie112/FactoriGOChatBot-companion/releases/tag/v0.7.3

It is also pushed to the Factorio Mod Portal:
https://mods.factorio.com/mod/FactoriGOChatBot-companion/downloads

Thanks for reporting it!

**Comment by dakkinbyte** [comment]
Thank you very much! Love being able to contribute to fixes within the community! Thanks again.
